### ISSUE TITLE
How can I build a website created using this boilerplate? 

### ISSUE THREAD

**Issue by DulanDev** [agragregra/OptimizedHTML-4#18]
I tried `gulp rsync` but it's getting failed. eventually I want to deploy this site to netlify..
```
[02:59:04] Starting 'rsync'...
[02:59:04] gulp-rsync: Starting rsync to username@yousite.com:yousite/public_html/...
[02:59:04] gulp-rsync: 'rsync' is not recognized as an internal or external command, [02:59:04] gulp-rsync:
[02:59:04] gulp-rsync: operable program or batch file. [02:59:04] gulp-rsync:
[02:59:04] gulp-rsync:  [02:59:04] 'rsync' errored after 151 ms
[02:59:04] Error in plugin 'gulp-rsync'
Message:
    Error: rsync exited with code 1
    at ChildProcess.<anonymous> (D:\Work\My Work\Projects\Pending\My Portfolio Website\Implementing\dulanhewage_portfolio\node_modules\gulp-rsync\rsync.js:110:17)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Socket.stream.socket.on (internal/child_process.js:346:11)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at Pipe._handle.close [as _onclose] (net.js:554:12)
[02:59:04] gulp-rsync: Completed rsync.

D:\Work\My Work\Projects\Pending\My Portfolio Website\Implementing\dulanhewage_portfolio>gulp rsync
[03:01:18] Using gulpfile D:\Work\My Work\Projects\Pending\My Portfolio Website\Implementing\dulanhewage_portfolio\gulpfile.js
[03:01:18] Starting 'rsync'...
[03:01:18] gulp-rsync: Starting rsync to username@yousite.com:yousite/public_html/...
[03:01:18] gulp-rsync: 'rsync' is not recognized as an internal or external command, [03:01:18] gulp-rsync:
[03:01:18] gulp-rsync: operable program or batch file. [03:01:18] gulp-rsync:
[03:01:18] gulp-rsync:  [03:01:18] 'rsync' errored after 127 ms
[03:01:18] Error in plugin 'gulp-rsync'
Message:
    Error: rsync exited with code 1
    at ChildProcess.<anonymous> (D:\Work\My Work\Projects\Pending\My Portfolio Website\Implementing\dulanhewage_portfolio\node_modules\gulp-rsync\rsync.js:110:17)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Socket.stream.socket.on (internal/child_process.js:346:11)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at Pipe._handle.close [as _onclose] (net.js:554:12)
[03:01:18] gulp-rsync: Completed rsync.
```

**Comment by kirillz** [comment]
`[02:59:04] gulp-rsync: Starting rsync to username@yousite.com:yousite/public_html/`

**Comment by DulanDev** [comment]
@kirillz I noticed that. but I don't the public directory name of netlify hosting

**Comment by vitaliy-tkachuk** [comment]
@Dulan666, then just edit line 53 of gulpfile.js according to your hosting folder structure :

destination: 'yoursite/public_html/',
